### ISSUE TITLE
Author name is not part of the article header

### ISSUE THREAD

**Issue by neil-c** [cariad/getcodelove.com-bugs#5]
I'll preface this with: this may be an unreasonable expectation.

It is often useful to find the author's name and the date of the article in the header (or at least somewhere on the article page).

Information can be less useful as the article ages. For example an article about a particular technology is great until a v2 of that technology comes out and the article then becomes less useful. A date of the post can easily allow a viewer to see if this is a recent article and may relate to current technology, or an older article which may still be useful to them.

**Comment by cariad** [comment]
Thanks, Neil! I totally agree, and I’ll pick this up in the next sprint (i.e. Saturday night).

**Comment by cariad** [comment]
Thanks again for raising this!
